"""Add scraping status tracking to search queries

Revision ID: e2195fed6d5c
Revises: 376ad166ceca
Create Date: 2025-09-22 21:12:25.575956

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2195fed6d5c'
down_revision: Union[str, Sequence[str], None] = '376ad166ceca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # First, clear existing offers since they don't have query_id
    op.execute('DELETE FROM offers')
    
    # Add the new columns
    op.add_column('offers', sa.Column('query_id', sa.Integer(), nullable=False))
    op.add_column('search_queries', sa.Column('last_scraped_at', sa.DateTime(), nullable=True))
    op.add_column('search_queries', sa.Column('last_scrape_count', sa.Integer(), nullable=True))
    op.add_column('search_queries', sa.Column('last_scrape_status', sa.String(), nullable=True))
    op.add_column('search_queries', sa.Column('last_scrape_error', sa.Text(), nullable=True))
    
    # Skip creating foreign key constraint for SQLite - SQLAlchemy will handle it at the ORM level
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('search_queries', 'last_scrape_error')
    op.drop_column('search_queries', 'last_scrape_status')
    op.drop_column('search_queries', 'last_scrape_count')
    op.drop_column('search_queries', 'last_scraped_at')
    op.drop_column('offers', 'query_id')
    # ### end Alembic commands ###
